## PyTroch Basics

This is the first tutorial for learning the basics of the PyTorch and becoming more familiar with it's features.

In [1]:
import torch
import torchvision

Checking whether the cuda is available or not (i.e., the code can be run on the GPU ro not).

In [2]:
print(torch.cuda.is_available())

True


### Torch Tensors

In [3]:
# This is a 1-D Tensor
a = torch.Tensor([2, 2, 1])
print(a)

tensor([2., 2., 1.])


In [4]:
# This is a 2-D Tensor
b = torch.Tensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
print(b)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])


In [5]:
# The size of the tensors
print(a.shape)
print(b.shape)
print(a.size())
print(b.size())

torch.Size([3])
torch.Size([4, 3])
torch.Size([3])
torch.Size([4, 3])


In [6]:
# Get the height/rows of the be
print(b.shape[0])

4


Tensors can have different data types. e.g., float32, float64, ...

In [7]:
c = torch.FloatTensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
print(c)
print(c.dtype)
# c = torch.Tensor([2, 1, 4], dtype=torch.float)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]])
torch.float32


In [8]:
d = torch.DoubleTensor([[2, 1, 4], [3, 5, 4], [1, 2, 0], [4, 3, 2]])
print(d)
print(d.dtype)
# c = torch.Tensor([2, 1, 4], dtype=torch.double)

tensor([[2., 1., 4.],
        [3., 5., 4.],
        [1., 2., 0.],
        [4., 3., 2.]], dtype=torch.float64)
torch.float64


In [9]:
print(c.mean())
print(c.std())

tensor(2.5833)
tensor(1.5050)


In [10]:
print(d.mean())
print(d.std())

tensor(2.5833, dtype=torch.float64)
tensor(1.5050, dtype=torch.float64)


Most of the time, during implementing deep learning algorithm, you need to reshape the tensor. Reshaping th tensor is very easy in the PyTorch.

In [11]:
# Reshape b
print(b.view(-1, 1))
print(b.view(12))
print(b.view(-1, 4))
print(b.view(3, 4))

# Assigning b a new shape
b = b.view(-1, 1)
print(b)
print(b.shape)

tensor([[2.],
        [1.],
        [4.],
        [3.],
        [5.],
        [4.],
        [1.],
        [2.],
        [0.],
        [4.],
        [3.],
        [2.]])
tensor([2., 1., 4., 3., 5., 4., 1., 2., 0., 4., 3., 2.])
tensor([[2., 1., 4., 3.],
        [5., 4., 1., 2.],
        [0., 4., 3., 2.]])
tensor([[2., 1., 4., 3.],
        [5., 4., 1., 2.],
        [0., 4., 3., 2.]])
tensor([[2.],
        [1.],
        [4.],
        [3.],
        [5.],
        [4.],
        [1.],
        [2.],
        [0.],
        [4.],
        [3.],
        [2.]])
torch.Size([12, 1])


In [13]:
# We can even reshape 3-D tensors
three_dim = torch.randn(2, 3, 4)
print('\n')
print(three_dim)
print(three_dim.view(2, 12)) # Reshape to 2 rows, 12 columns
print(three_dim.view(2, -1))



tensor([[[ 0.6245,  0.3755,  0.4193,  0.4085],
         [-0.4841,  2.8343, -0.6126,  1.4198],
         [ 0.1093, -0.3879,  0.2456, -0.4983]],

        [[ 0.1639, -0.2615, -0.1349,  0.6453],
         [-0.4531, -1.0474,  0.2032,  0.6496],
         [ 1.1529, -1.2491, -0.2669,  0.7748]]])
tensor([[ 0.6245,  0.3755,  0.4193,  0.4085, -0.4841,  2.8343, -0.6126,  1.4198,
          0.1093, -0.3879,  0.2456, -0.4983],
        [ 0.1639, -0.2615, -0.1349,  0.6453, -0.4531, -1.0474,  0.2032,  0.6496,
          1.1529, -1.2491, -0.2669,  0.7748]])
tensor([[ 0.6245,  0.3755,  0.4193,  0.4085, -0.4841,  2.8343, -0.6126,  1.4198,
          0.1093, -0.3879,  0.2456, -0.4983],
        [ 0.1639, -0.2615, -0.1349,  0.6453, -0.4531, -1.0474,  0.2032,  0.6496,
          1.1529, -1.2491, -0.2669,  0.7748]])


It is very easy to create tensors with random numbers in PyTorch.

In [14]:
# Create a matrix with random numbers between 0 and 1
r = torch.rand(4, 4)
print(r)

tensor([[0.4789, 0.3377, 0.3114, 0.0033],
        [0.0157, 0.3440, 0.0574, 0.6555],
        [0.4508, 0.1506, 0.7951, 0.5188],
        [0.3561, 0.2158, 0.1873, 0.1856]])


In [15]:
# Create a matrix with random numbers taken from normal distribution with mean 0 and variance 1
r2 = torch.randn(4, 4)
print(r2)
print(r2.dtype)

tensor([[ 1.2168, -0.4469, -0.3337,  1.5231],
        [ 1.5518, -1.5620,  0.8077, -0.5474],
        [-0.1191, -0.1836, -0.9880, -0.7081],
        [ 1.6474,  0.3013,  0.0343, -0.7250]])
torch.float32


In [21]:
# Create an array of 5 random integers from values between 6 and 9 (exlusive of 10)
in_array = torch.randint(6, 10, (5,))
print(in_array)
print(in_array.dtype)

tensor([9., 6., 9., 9., 9.])
torch.float32


In [22]:
# Create a matrix of 3*3 filled with random integers from values between 6 and 9 (exlusive of 10)
in_array2 = torch.randint(6, 10, (3, 3))
print(in_array2)
print(in_array2.dtype)

tensor([[8., 6., 9.],
        [7., 8., 7.],
        [6., 9., 8.]])
torch.float32


In [23]:
# Get the number of elements in an array
print(torch.numel(in_array))
# Get the number of elements in an array
print(torch.numel(in_array2))

5
9


In [24]:
# Create a 3*3 matrix of zeros and of type long
z = torch.zeros(3, 3, dtype=torch.double)
print(z)

# Create a 3*3 matrix of ones
o = torch.ones(3, 3)
print(o)
print(o.dtype)

tensor([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])
torch.float32


In [25]:
r2_like = torch.randn_like(r2, dtype=torch.double)   # Convert the data type of the tensor
print(r2_like)

tensor([[ 0.3533, -0.0631,  1.0018, -0.8785],
        [-0.5643,  1.8327, -0.0055, -0.2137],
        [-0.1128, -1.0893, -1.2280, -0.7310],
        [ 0.5856,  0.2191, -0.1514, -2.3133]], dtype=torch.float64)


In [29]:
# Add two tensors, make sure they are the same size and data type. Otherwise, it throws an error.
add_result = torch.add(r, r2)
print(add_result)

tensor([[ 1.6957, -0.1092, -0.0223,  1.5264],
        [ 1.5675, -1.2180,  0.8651,  0.1080],
        [ 0.3317, -0.0331, -0.1929, -0.1892],
        [ 2.0035,  0.5171,  0.2216, -0.5394]])


In [33]:
# In place addition (change the value of r2).
r2.add_(r)  # Same as r2 = torch.add(r, r2)
print(r2)

tensor([[ 3.1323,  0.9039,  0.9118,  1.5363],
        [ 1.6146, -0.1861,  1.0375,  2.0745],
        [ 1.6842,  0.4186,  2.1924,  1.3673],
        [ 3.0720,  1.1643,  0.7835,  0.0174]])


In [38]:
# Matrix Slicing in PyTorch
print(r2[:, 1])
print(r2[:, :2])
print(r2[:3, :])
print(r2[2, :])
num_ten = r2[2, 3]
print(num_ten)
# Use torch.Tensor.item() to get a Python number from a tensor containing a single value
print(num_ten.item())

tensor([ 0.9039, -0.1861,  0.4186,  1.1643])
tensor([[ 3.1323,  0.9039],
        [ 1.6146, -0.1861],
        [ 1.6842,  0.4186],
        [ 3.0720,  1.1643]])
tensor([[ 3.1323,  0.9039,  0.9118,  1.5363],
        [ 1.6146, -0.1861,  1.0375,  2.0745],
        [ 1.6842,  0.4186,  2.1924,  1.3673]])
tensor([1.6842, 0.4186, 2.1924, 1.3673])
tensor(1.3673)
1.367262601852417


### Numpy Bridge

It is easy to convert a torch.Tensor object to numpy array and vice versa.

In [40]:
import numpy as np

In [44]:
# Converting a torch tensor to numpy array
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [45]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [48]:
a.add_(1)
print(a)
print(b)    # see how the numpy array changed in value

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]
